/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TouristPlace = IDL.Record({
  'id' : IDL.Nat,
  'mapsUrl' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ItineraryDayLabel = IDL.Record({
  'day' : IDL.Nat,
  'places' : IDL.Vec(IDL.Nat),
  'dayLabel' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTouristPlace' : IDL.Func([TouristPlace], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearMyItinerary' : IDL.Func([], [], []),
  'deleteTouristPlace' : IDL.Func([IDL.Nat], [], []),
  'getAllTouristPlaces' : IDL.Func([], [IDL.Vec(TouristPlace)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyItinerary' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(ItineraryDayLabel))],
      ['query'],
    ),
  'getPlacesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TouristPlace)],
      ['query'],
    ),
  'getTouristPlace' : IDL.Func([IDL.Nat], [TouristPlace], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveMyItinerary' : IDL.Func([IDL.Vec(IDL.Vec(ItineraryDayLabel))], [], []),
  'updateTouristPlace' : IDL.Func([TouristPlace], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TouristPlace = IDL.Record({
    'id' : IDL.Nat,
    'mapsUrl' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ItineraryDayLabel = IDL.Record({
    'day' : IDL.Nat,
    'places' : IDL.Vec(IDL.Nat),
    'dayLabel' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTouristPlace' : IDL.Func([TouristPlace], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearMyItinerary' : IDL.Func([], [], []),
    'deleteTouristPlace' : IDL.Func([IDL.Nat], [], []),
    'getAllTouristPlaces' : IDL.Func([], [IDL.Vec(TouristPlace)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyItinerary' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(ItineraryDayLabel))],
        ['query'],
      ),
    'getPlacesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TouristPlace)],
        ['query'],
      ),
    'getTouristPlace' : IDL.Func([IDL.Nat], [TouristPlace], ['query']),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveMyItinerary' : IDL.Func([IDL.Vec(IDL.Vec(ItineraryDayLabel))], [], []),
    'updateTouristPlace' : IDL.Func([TouristPlace], [], []),
  });
};

export const init = ({ IDL }) => { return []; };